# Generated by Django 5.1.1 on 2024-09-19 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('videojuegos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='alquiler',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cliente', models.CharField(max_length=100)),
                ('fecha_alquiler', models.DateTimeField()),
                ('fecha_devolucion', models.DateTimeField(blank=True, null=True)),
                ('videojuego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videojuegos.videojuegos')),
            ],
        ),
    ]
