# Generated by Django 5.1.1 on 2024-09-20 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alquiler',
            name='estado',
            field=models.CharField(default='Sin estado', max_length=100, null=True),
        ),
    ]
