# Generated by Django 5.1.1 on 2024-09-19 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genero', '0001_initial'),
        ('plataforma', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='videojuegos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('stock', models.IntegerField()),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genero.genero')),
                ('plataforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.plataforma')),
            ],
        ),
    ]
