# Generated by Django 5.1.1 on 2024-09-20 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0001_initial'),
        ('genero', '0001_initial'),
        ('plataforma', '0001_initial'),
        ('videojuegos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='videojuegos',
            new_name='videojuego',
        ),
    ]
